openapi: 3.0.0
info:
  description: "Реализованы 3 сервиса: заказа, биллинга, нотификаций. При создании пользователя создается аккаунт в сервисе биллинга, в котором есть возможность положить деньги на аккаунт и снять деньги. Сервис нотификаций позволяет отправить сообщение на email и получить список отправленных сообщений"
  version: "1.0.0"
  title: OTUS Software Architecture HW6
tags:
  - name: orders
    description: Сервис работы с заказами
  - name: billing
    description: Сервис биллинга
  - name: notification
    description: Сервис нотификаций
paths:
  /orders:
    post:
      tags:
        - orders
      summary: Создание заказа
      operationId: createOrder
      description: |
        Создание заказа для пользователя с указанием цены
      requestBody:
        $ref: '#/components/requestBodies/OrderCreation'
      responses:
        '201':
          description: Заказ создан и оплачен
        '400':
          description: Неверный запрос
        '408':
          description: Таймаут
        default:
          description: Ошибка при создании и обработке заказа
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /orders/{orderId}:
    get:
      tags:
        - orders
      summary: Получение информации о заказе
      operationId: getOrderInfo
      description: |
        Получение информации о заказе
      parameters:
        - name: orderId
          in: path
          description: ID заказа
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Неверный запрос
        '404':
          description: Заказ не существует
        '408':
          description: Таймаут
  /billing/user:
    post:
      tags:
        - billing
      summary: Создание пользователя
      operationId: createUser
      description: |
        Создание пользователя
      requestBody:
        $ref: '#/components/requestBodies/UserCreation'
      responses:
        '201':
          description: Пользователь создан
        '400':
          description: Неверный запрос
        '408':
          description: Таймаут
        default:
          description: Ошибка при создании пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /billing/user/{userId}:
    get:
      tags:
        - billing
      summary: Получение информации о пользователе
      operationId: getUserInfo
      description: |
        Получение информации о пользователе
      parameters:
        - name: userId
          in: path
          description: ID пользователя
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Неверный запрос
        '404':
          description: Пользователя не существует
        '408':
          description: Таймаут
  /billing/deposit/{userId}:
    post:
      tags:
        - billing
      summary: Пополнение баланса пользователя
      operationId: deposit
      description: |
        Пополнение баланса пользователя
      parameters:
        - name: userId
          in: path
          description: ID пользователя
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MonetaryAmount'
        required: true
      responses:
        '200':
          description: Успешный запрос
        '400':
          description: Неверный запрос
        '408':
          description: Таймаут
        default:
          description: Ошибка при пополнении баланса пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /billing/withdraw/{userId}:
    post:
      tags:
        - billing
      summary: Снятие средств с баланса пользователя
      operationId: withdraw
      description: |
        Снятие средств с баланса пользователя
      parameters:
        - name: userId
          in: path
          description: ID пользователя
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MonetaryAmount'
        required: true
      responses:
        '200':
          description: Успешный запрос
        '400':
          description: Неверный запрос
        '408':
          description: Таймаут
        default:
          description: Ошибка при снятии средств с баланса пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /notification/email/{userId}:
    get:
      tags:
        - notification
      summary: Получение отправленных email для пользователя
      operationId: getUserEmails
      description: |
        Получение отправленных email для пользователя
      parameters:
        - name: userId
          in: path
          description: ID пользователя
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: object
                properties:
                  emails:
                    type: array
                    items:
                      $ref: '#/components/schemas/EmailContent'
        '400':
          description: Неверный запрос
        '408':
          description: Таймаут
    post:
      tags:
        - notification
      summary: Отправка email пользователю
      operationId: sendUserEmail
      description: |
        Отправка email пользователю
      parameters:
        - name: userId
          in: path
          description: ID пользователя
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailContent'
        required: true
      responses:
        '202':
          description: Задача отправки email для пользователя поставлена в очередь
        '400':
          description: Неверный запрос
        '404':
          description: Пользователя не существует
        '408':
          description: Таймаут
        default:
          description: Ошибка при создании пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    MonetaryAmount:
      type: object
      required:
        - amount
        - currency
      properties:
        amount:
          type: string
        currency:
          type: string
          maxLength: 3
    Order:
      type: object
      required: 
          - id
          - userId
          - price
          - status
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        price:
          $ref: '#/components/schemas/MonetaryAmount'
        status:
          type: integer
          format: int64
    User:
      type: object
      required: 
          - id
          - username
          - firstName
          - lastName
          - email
          - phone
          - balance
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
          maxLength: 256
        firstName:
          type: string
          maxLength: 256
        lastName:
          type: string
          maxLength: 256
        email:
          type: string
          format: email
          maxLength: 256
        phone:
          type: string
          format: phone
          maxLength: 256
        balance:
          $ref: '#/components/schemas/MonetaryAmount'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    EmailContent:
      type: object
      required:
        - title
        - message
      properties:
        title:
          type: integer
          format: string
          maxLength: 256
        message:
          type: string
  requestBodies:
    OrderCreation:
      content:
        application/json:
          schema:
            type: object
            required: 
                - userId
                - price
            properties:
              userId:
                type: number
              price:
                $ref: '#/components/schemas/MonetaryAmount'
      description: Информация для создания заказа
      required: true
    UserCreation:
      content:
        application/json:
          schema:
            type: object
            required: 
                - username
                - password
                - email
            properties:
              username:
                type: string
                maxLength: 256
              password:
                type: string
                format: password
                maxLength: 256
              firstName:
                type: string
                maxLength: 256
              lastName:
                type: string
                maxLength: 256
              email:
                type: string
                format: email
                maxLength: 256
              phone:
                type: string
                format: phone
                maxLength: 256
      description: Информация для создания пользователя
      required: true